### ISSUE TITLE
NFS client provisioner stops working in OpenShift 4.8

### ISSUE THREAD

**Issue by koep** [RedHat-EMEA-SSA-Team/hetzner-ocp4#175] opened 2021-05-03 08:02 UTC
Running OpenShift 4.8.0-fc.2 with Kubernetes 1.21.0 causes the NFS provisioner to stop working.

Using one of the [later versions](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) (`k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2`) seems to fix the issue.

However, I have not tested whether or not this version of the nfs provisioner works on any version below 4.8.

**Comment by lucamaf** [comment] 2021-05-12 15:30
this is caused by https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25#issuecomment-742616668
and the suggestion is to move to the latest version of the nfs client provisioner which was adopted under an openshift sig
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

**Comment by rbo** [comment] 2021-05-14 11:34
Just-for-information, and might be worth checking/update the docs.:
https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client is moved into https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

**Comment by rbo** [comment] 2021-05-14 11:42
oh, we still use the `quay.io/external_storage/nfs-client-provisioner:latest` and that's quite old. 

Update image to `k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2` in devel tree for further testings.

**Comment by rbo** [comment] 2021-07-26 14:49
Solved in devel, will me merged into master with  PR #183  - (Devel branch is at OCP 4.8.2)

**Closed by rbo** 2021-07-26 14:49 UTC
