### ISSUE TITLE
host-passthough not working on CentOS Stream 8

### ISSUE THREAD

**Issue by iboernig** [RedHat-EMEA-SSA-Team/hetzner-ocp4#163] opened 2020-12-21 17:49 UTC
Using CentOS 8 Stream I encountered another issue:
VMs flagged with "host-passthrough" (for nested virtualization)
```
compute_special_cpu: "<cpu mode='host-passthrough'></cpu>"
master_special_cpu: "<cpu mode='host-passthrough'></cpu>"
```
result in a "paused" state in virt-manager.
After changing back to the default behavior it works again.

```
[root@bigmachine hetzner-ocp4]# uname -a
Linux bigmachine 4.18.0-257.el8.x86_64 #1 SMP Thu Dec 3 22:16:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@bigmachine hetzner-ocp4]# cat /etc/centos-release 
CentOS Stream release 8
[root@bigmachine hetzner-ocp4]# cat /etc/modprobe.d/kvm.conf
options kvm_intel nested=1
```

**Comment by rbo** [comment] 2020-12-22 08:00
For "host-passthrough" your [master|compute]_special_cpu have to be: `<cpu mode='host-passthrough'></cpu>`

Installed Centos 8 on Hetzner and converting to Centos 8 Stream:
```
dnf -y update
dnf -y install centos-release-stream
dnf -y swap centos-{linux,stream}-repos
dnf -y distro-sync
```

```
$ cat /etc/centos-release
CentOS Stream release 8
$ grep -v ^# /etc/modprobe.d/kvm.conf
options kvm_intel nested=1
$ cat /sys/module/kvm_intel/parameters/nested
1
```

Uf during cluster installation, I run into https://github.com/ansible/ansible/issues/71528

```
TASK [openshift-4-cluster : Enable & Start firewalld] ***************************************************************
Tuesday 22 December 2020  08:04:42 +0100 (0:00:01.107)       0:00:03.209 ******
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
```

```
$ rpm -qa | grep -E '(systemd|ansible)'
ansible-2.9.15-1.el8.noarch
systemd-libs-239-43.el8.x86_64
systemd-container-239-43.el8.x86_64
systemd-239-43.el8.x86_64
systemd-pam-239-43.el8.x86_64
python3-systemd-234-8.el8.x86_64
systemd-udev-239-43.el8.x86_64
rpm-plugin-systemd-inhibit-4.14.3-4.el8.x86_64
```

:-(

**Comment by rbo** [comment] 2020-12-22 10:25
> Using CentOS 8 Stream I encountered another issue:
> VMs flagged with "host-passthrough" (for nested virtualization)
> 
> compute_special_cpu: ""
> master_special_cpu: ""
>
Please use [Markdown code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code), it looks like *_special_cpu is empty. 

I will update your comment.

**Comment by iboernig** [comment] 2020-12-22 10:41
You need to update to ansible-2.9.16 in order to work around this systemd
bug.
It is available in CentOS Stream 8 since a few days.


Robert Bohne <notifications@github.com> schrieb am Di., 22. Dez. 2020,
09:01:

**Comment by rbo** [comment] 2020-12-22 12:03
ARG 🤦🏼  forgot to run `yum install -y centos-release-ansible-29.noarch` as documented...

**Comment by rbo** [comment] 2020-12-22 12:52
Installation work in progress, based on devel tree.
```
$ virsh list
 Id   Name             State
--------------------------------
 2    demo2-master-0   running
 3    demo2-master-1   running
 4    demo2-master-2   running
```

**Comment by rbo** [comment] 2020-12-22 13:01
How many vcpu's do you have available? `grep vendor_id /proc/cpuinfo  | wc -l`
Default cluster sizing? 
Might be a problem with vCPU overcommitment?

**Comment by iboernig** [comment] 2020-12-22 13:13
[root@bigmachine hetzner-ocp4]# grep vendor_id /proc/cpuinfo | wc -l
12
Yes, overcommitment is involved, but that has never been a problem before. And we are not doing any pinning here. But maybe that has changed.

**Comment by rbo** [comment] 2020-12-22 14:35
I can not reproduce, installation works perfectly.

**Comment by rbo** [comment] 2020-12-23 08:20
I will close the issue, it looks like it is a KVM problem. Let me know it the problem still exists, maybe you can get me access to the box.

**Closed by rbo** 2020-12-23 08:20 UTC
