### ISSUE TITLE
renewing certificate using the playbook fails 

### ISSUE THREAD

**Issue by lucamaf** [RedHat-EMEA-SSA-Team/hetzner-ocp4#145] opened 2020-11-17 15:21 UTC
I'm using OCP 4.6 and on trying to renew let's encrypt certificates I get an authentication error when executing TASK [openshift-4-cluster : Create secret with certificates for openshift-ingress]:

```
  File "/usr/lib/python3.6/site-packages/openshift/dynamic/client.py", line 44, in inner
    raise api_exception(e)
openshift.dynamic.exceptions.UnauthorizedError: 401
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '62d10672-e8ad-4f73-a80b-d7a04c05f6dd', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 17 Nov 2020 11:16:12 GMT', 'Content-Length': '129'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}\n'

```

although when trying to execute a simple python k8s program I had no issue in authenticating and listing projects.

**Comment by rbo** [comment] 2020-12-22 14:36
> although when trying to execute a simple python k8s program I had no issue in authenticating and listing projects.

Do you have details about the simple python k8s program?

**Comment by lucamaf** [comment] 2021-01-04 11:32
here it is https://pastebin.com/raw/R6xqYfhn

**Comment by rbo** [comment] 2021-01-05 07:41
It looks to me your kubeconfig was / (is?) broken. 

```bash
$ export KUBECONFIG=/root/hetzner-ocp4/demo/auth/kubeconfig
$ oc get nodes
NAME       STATUS   ROLES           AGE     VERSION
master-0   Ready    master,worker   4d11h   v1.19.0+7070803
master-1   Ready    master,worker   4d11h   v1.19.0+7070803
master-2   Ready    master,worker   4d11h   v1.19.0+7070803
$ python3
Python 3.6.8 (default, Aug 18 2020, 08:33:21)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import client, config
>>> from openshift.dynamic import DynamicClient
>>> k8s_client = config.new_client_from_config()
>>> dyn_client = DynamicClient(k8s_client)
>>> v1_projects = dyn_client.resources.get(api_version='project.openshift.io/v1', kind='Project')
>>> project_list = v1_projects.get()
>>> for project in project_list.items:
...     print(project.metadata.name)
...
bouvier
default
foobar
kube-node-lease
kube-public
kube-system
openshift
openshift-apiserver
openshift-apiserver-o
```

Mh, next time please check your kubeconfig with:
```bash
$ export KUBECONFIG=/root/hetzner-ocp4/.../auth/kubeconfig
$ oc get nodes
```
Please keep in mind if you use 
```bash
export KUBECONFIG=/root/hetzner-ocp4/.../auth/kubeconfig
oc project ...
oc login ...
```
You (oc tool) change the kubeconfig, and some further automation might fail. 

The context has to be `admin` to have a propper working automation:
```bash
$ oc config current-context
admin
$ oc config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://api.demo.openshift.pub:6443
  name: demo
contexts:
- context:
    cluster: demo
    user: admin
  name: admin
current-context: admin
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
$
```

Does the problem still exist?
If not I suggest closing the issue. Because I can not reproduce. 
If it still exists, please check your kubeconfig.

**Comment by rbo** [comment] 2021-03-19 14:59
No response => closed. Feel free to reopen.

**Closed by rbo** 2021-03-19 14:59 UTC
Labels: question
